// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFfEV2UnWNsDpyvKSHWzveC6xisWryeVw',
    appId: '1:577681419707:web:3028cc799e3dd01f4f689e',
    messagingSenderId: '577681419707',
    projectId: 'difwa-7aea2',
    authDomain: 'difwa-7aea2.firebaseapp.com',
    databaseURL: 'https://difwa-7aea2-default-rtdb.firebaseio.com',
    storageBucket: 'difwa-7aea2.firebasestorage.app',
    measurementId: 'G-N6J8WC5XQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAJaqi1ut9ZhSKvoRrO-quVwlmrgjAmYM',
    appId: '1:577681419707:android:b72d093cccce731c4f689e',
    messagingSenderId: '577681419707',
    projectId: 'difwa-7aea2',
    databaseURL: 'https://difwa-7aea2-default-rtdb.firebaseio.com',
    storageBucket: 'difwa-7aea2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARpAphlc4yWvlACj6OFc0TdLKatOKkEbA',
    appId: '1:577681419707:ios:f8c2877d311320004f689e',
    messagingSenderId: '577681419707',
    projectId: 'difwa-7aea2',
    databaseURL: 'https://difwa-7aea2-default-rtdb.firebaseio.com',
    storageBucket: 'difwa-7aea2.firebasestorage.app',
    iosClientId: '577681419707-oviboc7o0u2grs6871b87ftash16t9ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.difwaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARpAphlc4yWvlACj6OFc0TdLKatOKkEbA',
    appId: '1:577681419707:ios:f8c2877d311320004f689e',
    messagingSenderId: '577681419707',
    projectId: 'difwa-7aea2',
    databaseURL: 'https://difwa-7aea2-default-rtdb.firebaseio.com',
    storageBucket: 'difwa-7aea2.firebasestorage.app',
    iosClientId: '577681419707-oviboc7o0u2grs6871b87ftash16t9ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.difwaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFfEV2UnWNsDpyvKSHWzveC6xisWryeVw',
    appId: '1:577681419707:web:edaa9bfa9792e3914f689e',
    messagingSenderId: '577681419707',
    projectId: 'difwa-7aea2',
    authDomain: 'difwa-7aea2.firebaseapp.com',
    databaseURL: 'https://difwa-7aea2-default-rtdb.firebaseio.com',
    storageBucket: 'difwa-7aea2.firebasestorage.app',
    measurementId: 'G-NNR4W19LQM',
  );
}
